version: "0.1"
user: gagandeepb
key: wzgRUvmhiGodczTuOWhY0IkITni78467mDrYTFzbFwAMlMqaO7
matrix: {browser: ['MicrosoftEdge:latest:Windows10@lambdatest', 'chrome:108:Windows10@lambdatest', 'pw-firefox:latest@lambdatest'], methods: [tests/sample.spec.ts, tests/pageTitle.spec.ts, tests/searchbox.spec.ts, verifyMsg.spec.ts], os: [win, linux]}
testSuites: [npx playwright test --project=$browser $methods]
pre: [npm install, npx playwright install]
preDirectives:
    commands: [npm install, npx playwright install]
    maxRetries: 0
    shell: ""
    workingDirectory: ""
postDirectives:
    commands: []
    shell: ""
    workingDirectory: ""
runson: ${matrix.os}
tunnelNames:
    - rXtisedNrXGQKuMw
cacheDirectories:
    - node_modules
cacheKey: '{{ checksum "package-lock.json" }}'
retryOnFailure: true
maxRetries: 1
jobID: c120ca60-c004-4d50-a07c-5c68cdbfbb5d
codeDirectory: ContosoTraders.Ui.Website
framework:
    name: ""
    flags: []
    discoveryFlags: []
    discoveryType: ""
    runnerFlags: []
    workingDirectory: ""
    isTestNGXMLSuite: false
    defaultReports: true
    additional_args: null
    licenseKey: ""
    userdefinediscovery: false
    toscaArgs: null
    version: ""
cypress: false
betaFeature:
    setPartiallyCompletedAsCompleted: false
testType: playwright
combineTasksInMatrixMode: false
captureScreenRecordingForScenarios: false
maxRetriesPreSteps: 0
triggerMode: false
collectLocalGitData: false
