version: "0.1"
user: gagandeepb
key: wzgRUvmhiGodczTuOWhY0IkITni78467mDrYTFzbFwAMlMqaO7
testSuites: []
pre: [npm install, npx playwright install, npm run build]
preDirectives:
    commands: [npm install, npx playwright install, npm run build]
    maxRetries: 0
    shell: ""
    workingDirectory: ""
postDirectives:
    commands: []
    shell: ""
    workingDirectory: ""
runson: win
autosplit: true
concurrency: 3
testDiscovery:
    autosubset: true
    command: grep -lr 'describe' tests -ir --include=*spec.ts
    mode: dynamic
    type: raw
testRunnerCommand: npx playwright test $test
globalTimeout: 90
tunnelOpts:
    global: true
tunnelNames:
    - ZkQOSnRuxRytlEHG
testSuiteTimeout: 90
testSuiteStep: 90
cacheDirectories:
    - node_modules
cacheKey: '{{ checksum "package-lock.json" }}'
retryOnFailure: true
maxRetries: 1
jobID: c124332c-96d8-4afc-aec5-8d0daa6675f5
codeDirectory: ContosoTraders.Ui.Website
framework:
    name: ""
    flags: []
    discoveryFlags: []
    discoveryType: ""
    runnerFlags: []
    workingDirectory: ""
    isTestNGXMLSuite: false
    defaultReports: true
    additional_args: null
    licenseKey: ""
    userdefinediscovery: false
    toscaArgs: null
    version: ""
cypress: false
betaFeature:
    setPartiallyCompletedAsCompleted: false
testType: playwright
combineTasksInMatrixMode: false
captureScreenRecordingForScenarios: false
maxRetriesPreSteps: 0
triggerMode: false
collectLocalGitData: false
