
name: Github-coPilot Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      username:
        required: true
        description: LT Username
        default: gagandeepb
      accessKey:
        description: LT Access Key
        required: true
        default: wzgRUvmhiGodczTuOWhY0IkITni78467mDrYTFzbFwAMlMqaO7
jobs:
  HyperExecute-Playwright:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Starting CLI testing
        env:
          LT_USERNAME: ${{ secrets.LT_USERNAME }}
          LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
        shell: bash
        run: |
          echo "STEP 1 ) Downloading sample suite"
          git clone https://github.com/gagan-lambda/contosotraders-cloudtesting.git
          echo "STEP 2) Download CLI and setting environment variables"
              cd src/ContosoTraders.Ui.Website
              curl https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe -o hyperexecute.exe
              export LT_USERNAME=${{ github.event.inputs.username.default }}
              export LT_ACCESS_KEY=${{ github.event.inputs.accessKey.default }}
              echo $LT_USERNAME 
              echo $LT_ACCESS_KEY
              ./hyperexecute --user $LT_USERNAME --key $LT_ACCESS_KEY --config hyperExecute.yaml
